### ISSUE TITLE
SMP_SECURITY_REQUEST_COMMAND received before 'on_connection()'

### ISSUE THREAD

**Issue by ericcariat** [google/bumble#647]
I use bumble on the host connected through an HCI USB to an eval board nrf52840 DK running a Zephyr BLE HCI firmware.
Most of the time everything is OK, but sometimes, I receive the SMP_SECURITY_REQUEST_COMMAND before the on_connection() handler  (where I set all the handler and the one for the 'security_request'.... but in that case it's too late ... the SMP has been received a few millisecond before).

See in the Logs : 
While the host is requesting the HCI_LE_READ_PHY_COMMAND, we receive the SMP_SECURITY_REQUEST_COMMAND from the peripheral (this message is lost because we have not yet processed the on_connection), then the controller send the HCI_COMMAND_COMPLETE_EVENT, and it looks like from that moment bumble execute the on_connection, where I can start the security handler (but it already too late).
connection.on('security_request', lambda req: asyncio.create_task(self.on_smp_security_request(connection, req)))

Any way to install the 'security_request' in the Listener constructor without having a connection yet ?
Or any way to have the on_connection() earlier ?

thanks

Here is my class Listener : 

```
 class Listener(Device.Listener):
    ''' This class listens for connection events and handles security setup
        The 'on_connection' will start all security handlers
        Some event are used to synchronize the connection setup
        Args:   device (Device): the device object
    '''
    def __init__(self, device, logger):
        self.logger = logger
        self.device = device
        self.pairing_event = asyncio.Event()
        self.security_established = asyncio.Event()
        self.has_bonds = False
        self.device.on('connection', lambda connection: asyncio.ensure_future(self.on_connection(connection)))

    async def on_connection(self, connection):
        connection.on('security_request', lambda req: asyncio.create_task(self.on_smp_security_request(connection, req)))
        connection.on('disconnection', self.on_disconnection)

        self.logger.info(f"Connected to {connection.peer_address}")

        # Start all security event handlers
        connection.on('pairing_start', self.on_pairing_start)
        connection.on('pairing', self.on_pairing_complete)
        connection.on('pairing_failure', self.on_pairing_failure)
        connection.on('connection_encryption_change', self.on_encryption_change)

        if self.device.keystore is not None:
            keys = await self.device.keystore.get(str(connection.peer_address))
            if keys is not None:
                self.logger.info("Found keys !")
                self.has_bonds = True
```

Here is the Log when I receive the SMP_SECURITY_REQUEST_COMMAND just before the on_connection() :

```
`2025-02-13 01:10:27,221 [DEBUG] ### CONTROLLER -> HOST: HCI_COMMAND_STATUS_EVENT:
  status:                  PENDING
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_CREATE_CONNECTION_COMMAND
2025-02-13 01:10:27,233 [DEBUG] ### CONTROLLER -> HOST: HCI_LE_ENHANCED_CONNECTION_COMPLETE_EVENT:
  status:                           HCI_SUCCESS
  connection_handle:                0
  role:                             CENTRAL
  peer_address_type:                RANDOM_DEVICE_ADDRESS
  peer_address:                     C6:59:47:B8:5C:DE
  local_resolvable_private_address: 00:00:00:00:00:00
  peer_resolvable_private_address:  00:00:00:00:00:00
  connection_interval:              9
  peripheral_latency:               0
  supervision_timeout:              300
  central_clock_accuracy:           5
2025-02-13 01:10:27,233 [DEBUG] ### LE CONNECTION: [0x0000] C6:59:47:B8:5C:DE as CENTRAL
2025-02-13 01:10:27,233 [DEBUG] *** Connection: [0x0000] C6:59:47:B8:5C:DE CENTRAL
2025-02-13 01:10:27,234 [DEBUG] ### CONTROLLER -> HOST: ACL: handle=0x0000, pb=2, bc=0, data_total_length=7, data=0300040002f700
2025-02-13 01:10:27,235 [DEBUG] <<< ACL PDU: 0300040002f700
2025-02-13 01:10:27,235 [DEBUG] GATT Request to server: [0x0000] ATT_EXCHANGE_MTU_REQUEST:
  client_rx_mtu: 247
2025-02-13 01:10:27,236 [DEBUG] GATT Response from server: [0x0000] ATT_EXCHANGE_MTU_RESPONSE:
  server_rx_mtu: 517
2025-02-13 01:10:27,236 [DEBUG] >>> ACL packet enqueue: (CID=4) ACL: handle=0x0000, pb=0, bc=0, data_total_length=7, data=03000400030502
2025-02-13 01:10:27,236 [DEBUG] ### HOST -> CONTROLLER: ACL: handle=0x0000, pb=0, bc=0, data_total_length=7, data=03000400030502
2025-02-13 01:10:27,236 [DEBUG] *** Connection ATT MTU Update: [0x0000] C6:59:47:B8:5C:DE as CENTRAL, 247
2025-02-13 01:10:27,237 [DEBUG] ### HOST -> CONTROLLER: HCI_LE_READ_PHY_COMMAND:
  connection_handle: 0
2025-02-13 01:10:27,245 [DEBUG] ### CONTROLLER -> HOST: ACL: handle=0x0000, pb=2, bc=0, data_total_length=6, data=020006000b09
2025-02-13 01:10:27,245 [DEBUG] <<< ACL PDU: 020006000b09
2025-02-13 01:10:27,246 [DEBUG] <<< Received SMP Command on connection [0x0000] C6:59:47:B8:5C:DE: SMP_SECURITY_REQUEST_COMMAND:
  auth_req: bonding_flags=1, MITM=0, sc=1, keypress=0, ct2=0
2025-02-13 01:10:27,246 [DEBUG] ### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_READ_PHY_COMMAND
  return_parameters:       
    status:            HCI_SUCCESS
    connection_handle: 0
    tx_phy:            LE 1M
    rx_phy:            LE 1M
2025-02-13 01:10:27,247 [INFO] Connected to C6:59:47:B8:5C:DE
2025-02-13 01:10:27,249 [DEBUG] ### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:        1
  connection_handle[0]:     0
  num_completed_packets[0]: 1
2025-02-13 01:10:27,749 [INFO] Waiting for security to be established...
2025-02-13 01:10:32,755 [ERROR] Timeout waiting for security to be established
2025-02-13 01:10:32,755 [DEBUG] Cleaning up 2 pending tasks...
2025-02-13 01:10:32,756 [INFO] Retrying in 0.5 s
2025-02-13 01:10:33,257 [INFO] Connection attempt 2/2
2025-02-13 01:10:33,257 [DEBUG] Resetting connection states...`
```

**Comment by barbibulle** [comment]
You’re right, the connection event is delivered too late here. The reason for requesting the PHY before notifying of the connection was to avoid notify a connection with an unknown PHY first and then updating it, but I didn’t realize it could have this unintended consequence on the timing of the event. I’ll take a closer look shortly and propose a reasonable fix for this.

**Comment by barbibulle** [comment]
PR #649 should fix this issue. Could you try and check if it works for you?

**Comment by ericcariat** [comment]
mmmm ... Thanks for the fix! And yes I can see an improvement. It works most of the time.
but sometimes, I'm still receiving the SMP_SECURITY_REQUEST_COMMAND just before on_connection(), everything happening at the same millisecond.

I’m running the latest "main" branch with the fix (Bumble BLE library version: 0.0.208.dev9+g2c3af5b). 
Here’s a log where it still happens:

`2025-02-18 22:58:47,201 [DEBUG] ### CONTROLLER -> HOST: HCI_COMMAND_STATUS_EVENT:
  status:                  PENDING
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_CREATE_CONNECTION_COMMAND
2025-02-18 22:58:47,440 [DEBUG] ### CONTROLLER -> HOST: HCI_LE_ENHANCED_CONNECTION_COMPLETE_EVENT:
  status:                           HCI_SUCCESS
  connection_handle:                0
  role:                             CENTRAL
  peer_address_type:                RANDOM_DEVICE_ADDRESS
  peer_address:                     C6:59:47:B8:5C:DE
  local_resolvable_private_address: 00:00:00:00:00:00
  peer_resolvable_private_address:  00:00:00:00:00:00
  connection_interval:              9
  peripheral_latency:               3
  supervision_timeout:              300
  central_clock_accuracy:           5
2025-02-18 22:58:47,441 [DEBUG] ### LE CONNECTION: [0x0000] C6:59:47:B8:5C:DE as CENTRAL
2025-02-18 22:58:47,441 [DEBUG] *** Connection: [0x0000] C6:59:47:B8:5C:DE CENTRAL
2025-02-18 22:58:47,441 [DEBUG] ### CONTROLLER -> HOST: ACL: handle=0x0000, pb=2, bc=0, data_total_length=6, data=020006000b09
2025-02-18 22:58:47,441 [DEBUG] <<< ACL PDU: 020006000b09
2025-02-18 22:58:47,441 [DEBUG] <<< Received SMP Command on connection [0x0000] C6:59:47:B8:5C:DE: SMP_SECURITY_REQUEST_COMMAND:
  auth_req: bonding_flags=1, MITM=0, sc=1, keypress=0, ct2=0
2025-02-18 22:58:47,441 [INFO] Connected to C6:59:47:B8:5C:DE        **<= !!!! HERE I am in the on_connection handler (SMP already missed) !!!**
2025-02-18 22:58:47,441 [INFO] Found keys !
2025-02-18 22:58:47,451 [DEBUG] ### CONTROLLER -> HOST: ACL: handle=0x0000, pb=2, bc=0, data_total_length=7, data=0300040002f700
2025-02-18 22:58:47,451 [DEBUG] <<< ACL PDU: 0300040002f700
2025-02-18 22:58:47,451 [DEBUG] GATT Request to server: [0x0000] ATT_EXCHANGE_MTU_REQUEST:
  client_rx_mtu: 247
2025-02-18 22:58:47,451 [DEBUG] GATT Response from server: [0x0000] ATT_EXCHANGE_MTU_RESPONSE:
  server_rx_mtu: 517
2025-02-18 22:58:47,451 [DEBUG] >>> ACL packet enqueue: (CID=4) ACL: handle=0x0000, pb=0, bc=0, data_total_length=7, data=03000400030502
2025-02-18 22:58:47,451 [DEBUG] ### HOST -> CONTROLLER: ACL: handle=0x0000, pb=0, bc=0, data_total_length=7, data=03000400030502
2025-02-18 22:58:47,451 [DEBUG] *** Connection ATT MTU Update: [0x0000] C6:59:47:B8:5C:DE as CENTRAL, 247
2025-02-18 22:58:47,463 [DEBUG] ### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:        1
  connection_handle[0]:     0
  num_completed_packets[0]: 1
2025-02-18 22:58:47,943 [INFO] Enable encryption with stored keys
2025-02-18 22:58:48,445 [DEBUG] ### HOST -> CONTROLLER: HCI_LE_ENABLE_ENCRYPTION_COMMAND:`

**Comment by barbibulle** [comment]
This is puzzling.
The log line `2025-02-18 22:58:47,441 [DEBUG] *** Connection: [0x0000] C6:59:47:B8:5C:DE CENTRAL` is printed from the `Device.on_connection()` method, which will then call `self.emit('connection', connection)` which will call your listener. There is no `await` before calling `emit`, so there's no opportunity for any other code path to run before the listener.
In your case, is the log `2025-02-18 22:58:47,441 [INFO] Connected to C6:59:47:B8:5C:DE <= !!!! HERE I am in the on_connection handler (SMP already missed) !!!` something that's printed directly from the synchronous listener method you registered, or is it possible that you have that running in another async task, in which case, then, it would be entirely possible for it to run after the ACL packet with the SMP request is handled?
(in short, the log line `2025-02-18 22:58:47,441 [DEBUG] ### CONTROLLER -> HOST: ACL: handle=0x0000, pb=2, bc=0, data_total_length=6, data=020006000b09` can only be printed after the `Device.on_connection` method has returned, because all those methods run in the same async executor, and the `self.emit()` call being a synchronous call, all handlers will then have been called and have returned as well).

**Comment by ericcariat** [comment]
ah ... OK, I updated the "on_connection" registration in the listener __init__ 
from : 
`self.device.on('connection', lambda connection: asyncio.ensure_future(self.on_connection(connection)))`
To : 
`self.device.on('connection', self.on_connection)`
to ensure an immediate/synchronous call

My Listener looks like this now : 

    class Listener(Device.Listener):
        def __init__(self, device, logger):
            ...
            self.device.on('connection', self.on_connection)
    
        def on_connection(self, connection):
            # Start all event handlers
            connection.on('security_request', lambda req: asyncio.create_task(self.on_smp_security_request(connection, req)))
            connection.on('disconnection', self.on_disconnection)
            connection.on('pairing_start', self.on_pairing_start)
            connection.on('pairing', self.on_pairing_complete)
            connection.on('pairing_failure', self.on_pairing_failure)
            connection.on('connection_encryption_change', self.on_encryption_change)
            
            self.logger.info(f"Connected to {connection.peer_address}  has_bonds={self.has_bonds}")

Here is the successful trace for info : 

        2025-02-19 14:38:39,158 [DEBUG] ### LE CONNECTION: [0x0000] C6:59:47:B8:5C:DE as CENTRAL
        2025-02-19 14:38:39,158 [DEBUG] *** Connection: [0x0000] C6:59:47:B8:5C:DE CENTRAL
        2025-02-19 14:38:39,158 [INFO] Connected to C6:59:47:B8:5C:DE  has_bonds=True     => This is the on_connection handler
        2025-02-19 14:38:39,158 [DEBUG] ### CONTROLLER -> HOST: ACL: handle=0x0000, pb=2, bc=0, data_total_length=6, data=020006000b09
        2025-02-19 14:38:39,159 [DEBUG] <<< ACL PDU: 020006000b09
        2025-02-19 14:38:39,159 [DEBUG] <<< Received SMP Command on connection [0x0000] C6:59:47:B8:5C:DE: SMP_SECURITY_REQUEST_COMMAND:
          auth_req: bonding_flags=1, MITM=0, sc=1, keypress=0, ct2=0
        2025-02-19 14:38:39,159 [DEBUG] Received security request
        2025-02-19 14:38:39,159 [INFO] we have bonding info for this device - don't initiate pairing
        2025-02-19 14:38:39,168 [DEBUG] ### CONTROLLER -> HOST: ACL: handle=0x0000, pb=2, bc=0, data_total_length=7, data=0300040002f700
        2025-02-19 14:38:39,169 [DEBUG] <<< ACL PDU: 0300040002f700
        2025-02-19 14:38:39,169 [DEBUG] GATT Request to server: [0x0000] ATT_EXCHANGE_MTU_REQUEST:
          client_rx_mtu: 247
        2025-02-19 14:38:39,169 [DEBUG] GATT Response from server: [0x0000] ATT_EXCHANGE_MTU_RESPONSE:
          server_rx_mtu: 517
        2025-02-19 14:38:39,169 [DEBUG] >>> ACL packet enqueue: (CID=4) ACL: handle=0x0000, pb=0, bc=0, data_total_length=7, data=03000400030502
        2025-02-19 14:38:39,169 [DEBUG] ### HOST -> CONTROLLER: ACL: handle=0x0000, pb=0, bc=0, data_total_length=7, data=03000400030502
        2025-02-19 14:38:39,169 [DEBUG] *** Connection ATT MTU Update: [0x0000] C6:59:47:B8:5C:DE as CENTRAL, 247
        2025-02-19 14:38:39,181 [DEBUG] ### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
          number_of_handles:        1
          connection_handle[0]:     0
          num_completed_packets[0]: 1
        2025-02-19 14:38:41,161 [INFO] Enable encryption with stored keys
        2025-02-19 14:38:41,663 [DEBUG] ### HOST -> CONTROLLER: HCI_LE_ENABLE_ENCRYPTION_COMMAND:


Now it's working perfectly. Have made a stress tests of 50 successive connections, 
and it's always the exact same sequence.

Thanks for this patch, really appreciate your support. Everything is stable now
